#!/usr/bin/env bash
# test-run-checkers-version-drift.sh — regression guard for auto-force-full
# on scaffolder-version drift.
#
# Bug history:
#   0.2.1 attempted to detect "reviewer version changed" by reading
#   $SCRIPT_DIR/../SKILL.md (the skill that owns run-checkers.sh). But
#   run-checkers.sh is COPIED into every scaffolded target, so $SCRIPT_DIR/..
#   resolves to the target itself — its own version, not the scaffolder's.
#   Targets don't bump version when the scaffolder bumps; result was that
#   auto-force-full never triggered for any non-self-review target. The bug
#   accidentally worked for skill-forge reviewing skill-forge (because there
#   $SCRIPT_DIR/.. truly is skill-forge), which is why the original tests
#   passed.
#
#   0.2.2 fixes the resolution: scaffold.sh writes `scaffolder_version` into
#   $TARGET/common/scaffold-provenance.yml at scaffold/re-scaffold time. run-
#   checkers.sh reads that field. For self-review (no provenance file because
#   generators are not themselves scaffolded), it falls back to $TARGET/SKILL.md.
#
# Tests in this file MUST cover both the self-review path AND the previously-
# missed scaffolded-target path. A test that only walks the self-review path
# would have passed under the buggy 0.2.1 code — exactly what happened.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
SCRIPT="$HERE/../../scripts/run-checkers.sh"
SKILL_FORGE="$(cd "$HERE/../.." && pwd)"

[ -x "$SCRIPT" ] || { echo "FAIL: run-checkers.sh not executable"; exit 1; }

CURRENT_VERSION=$(grep -E '^version:' "$SKILL_FORGE/SKILL.md" | head -1 | sed -E 's/^version:[[:space:]]*//')

# ─────────────────────────────────────────────────────────────────────────────
# fixture builders
# ─────────────────────────────────────────────────────────────────────────────

# Build a SCAFFOLDED-TARGET fixture: target has its own SKILL.md (any version)
# AND a scaffold-provenance.yml carrying scaffolder_version. This is the
# common case and the one 0.2.1 missed.
build_scaffolded_fixture() {
  local target="$1"
  local target_skill_version="$2"   # the target's own SKILL.md version (NOT the scaffolder)
  local scaffolder_version="$3"     # value to embed in scaffold-provenance.yml
  local seen_version="$4"           # value for state.yml.reviewer_version_seen ('' to omit)
  mkdir -p "$target/scripts" "$target/common" "$target/.review"
  cat > "$target/common/review-criteria.md" <<'EOF'
# Review Criteria — fixture

## CR-LX1 placeholder

```yaml
- id: CR-LX1
  name: "placeholder"
  version: 1.0.0
  checker_type: llm
  severity: warning
  conflicts_with: []
  priority: 3
  incremental_skip: per_file
```
EOF
  cat > "$target/SKILL.md" <<EOF
---
name: fixture
version: $target_skill_version
description: "Use when running tests."
---

# fixture
EOF
  cat > "$target/common/scaffold-provenance.yml" <<EOF
# Auto-generated by scaffold.sh — DO NOT edit by hand.
scaffolder_version: "$scaffolder_version"
files:
EOF
  cat > "$target/.review/state.yml" <<EOF
skill_forge_dir: $SKILL_FORGE
delivery_id: 1
current_round: 1
target: $target
EOF
  if [ -n "$seen_version" ]; then
    echo "reviewer_version_seen: \"$seen_version\"" >> "$target/.review/state.yml"
  fi
}

# Build a SELF-REVIEW fixture: no scaffold-provenance.yml (the generator is
# not itself scaffolded). Falls back to $TARGET/SKILL.md.
build_self_review_fixture() {
  local target="$1"
  local target_skill_version="$2"
  local seen_version="$3"
  mkdir -p "$target/scripts" "$target/common" "$target/.review"
  cat > "$target/common/review-criteria.md" <<'EOF'
# Review Criteria — fixture

## CR-LX1 placeholder

```yaml
- id: CR-LX1
  name: "placeholder"
  version: 1.0.0
  checker_type: llm
  severity: warning
  conflicts_with: []
  priority: 3
  incremental_skip: per_file
```
EOF
  cat > "$target/SKILL.md" <<EOF
---
name: fixture
version: $target_skill_version
description: "Use when running tests."
---

# fixture
EOF
  cat > "$target/.review/state.yml" <<EOF
skill_forge_dir: $SKILL_FORGE
delivery_id: 1
current_round: 1
target: $target
EOF
  if [ -n "$seen_version" ]; then
    echo "reviewer_version_seen: \"$seen_version\"" >> "$target/.review/state.yml"
  fi
}

extract_forced() {
  grep '^forced_full:' "$1/.review/round-1/skip-set.yml" | awk '{print $2}'
}

extract_seen() {
  grep -E '^reviewer_version_seen:' "$1/.review/state.yml" | head -1 \
    | sed -E 's/^reviewer_version_seen:[[:space:]]*//' | sed -E 's/^"|"$//g'
}

cleanup() { rm -rf /tmp/rcv-test-*; }
trap cleanup EXIT

# ─────────────────────────────────────────────────────────────────────────────
# Test 1 — REGRESSION GUARD for the 0.2.1 bug
# Scaffolded target: target SKILL.md is "1.0.0" (unchanged), scaffolder_version
# is "0.2.2", state.yml's reviewer_version_seen is the OLD "0.2.1". This
# scenario is exactly the prd-analysis case post-skill-forge bump.
# Buggy 0.2.1 code read target/SKILL.md (1.0.0) and compared to seen (0.2.1)
# → match-or-no-match was wrong; in practice the target's version equals
# itself across rounds → never force-full.
# Fixed 0.2.2 code: reads scaffolder_version (0.2.2) from provenance file →
# differs from seen (0.2.1) → must force-full.
# ─────────────────────────────────────────────────────────────────────────────
T1=$(mktemp -d -t rcv-test-XXXXXX)
build_scaffolded_fixture "$T1" "1.0.0" "0.2.2" "0.2.1"
"$SCRIPT" "$T1" round-1 2>/tmp/rcv-stderr-$$ >/dev/null || true
F=$(extract_forced "$T1")
[ "$F" = "true" ] || {
  echo "FAIL Test 1 (regression guard for 0.2.1 bug): scaffolder_version drift on scaffolded target must force-full"
  echo "  target SKILL.md version: 1.0.0 (unchanged)"
  echo "  scaffold-provenance.yml scaffolder_version: 0.2.2"
  echo "  state.yml reviewer_version_seen: 0.2.1"
  echo "  expected forced_full: true; got: $F"
  cat /tmp/rcv-stderr-$$ >&2 || true
  exit 1
}
grep -qi 'scaffolder version' /tmp/rcv-stderr-$$ \
  || { echo "FAIL Test 1: stderr should announce 'scaffolder version' drift"; cat /tmp/rcv-stderr-$$ >&2; exit 1; }
S=$(extract_seen "$T1")
[ "$S" = "0.2.2" ] || { echo "FAIL Test 1: state.yml seen should advance to 0.2.2; got '$S'"; exit 1; }
rm -f /tmp/rcv-stderr-$$
echo "PASS Test 1: scaffolded-target drift (target SKILL unchanged, provenance bumped) → forced_full=true (regression guard for 0.2.1 bug)"

# ─────────────────────────────────────────────────────────────────────────────
# Test 2 — Scaffolded target, no drift
# Scaffolder version equals seen version → no force-full.
# ─────────────────────────────────────────────────────────────────────────────
T2=$(mktemp -d -t rcv-test-XXXXXX)
build_scaffolded_fixture "$T2" "1.0.0" "0.2.2" "0.2.2"
"$SCRIPT" "$T2" round-1 >/dev/null 2>&1 || true
F=$(extract_forced "$T2")
[ "$F" = "false" ] || { echo "FAIL Test 2: matching scaffolder_version expected forced_full=false; got $F"; exit 1; }
echo "PASS Test 2: scaffolded-target no drift → forced_full=false"

# ─────────────────────────────────────────────────────────────────────────────
# Test 3 — Self-review fallback path (skill-forge reviewing skill-forge)
# No provenance file. Read target's own SKILL.md. Drift detected against seen.
# ─────────────────────────────────────────────────────────────────────────────
T3=$(mktemp -d -t rcv-test-XXXXXX)
build_self_review_fixture "$T3" "$CURRENT_VERSION" "0.0.1-stale"
"$SCRIPT" "$T3" round-1 2>/tmp/rcv-stderr-$$ >/dev/null || true
F=$(extract_forced "$T3")
[ "$F" = "true" ] || { echo "FAIL Test 3: self-review version drift expected forced_full=true; got $F"; cat /tmp/rcv-stderr-$$ >&2; exit 1; }
grep -qi 'scaffolder version' /tmp/rcv-stderr-$$ \
  || { echo "FAIL Test 3: stderr should announce drift"; cat /tmp/rcv-stderr-$$; exit 1; }
S=$(extract_seen "$T3")
[ "$S" = "$CURRENT_VERSION" ] || { echo "FAIL Test 3: seen should advance to $CURRENT_VERSION; got '$S'"; exit 1; }
rm -f /tmp/rcv-stderr-$$
echo "PASS Test 3: self-review fallback (no provenance) → reads SKILL.md, detects drift"

# ─────────────────────────────────────────────────────────────────────────────
# Test 4 — First review (no prior reviewer_version_seen), scaffolded target
# Fresh target, no seen baseline. Don't auto-force on the first observation;
# just record the baseline for next round.
# ─────────────────────────────────────────────────────────────────────────────
T4=$(mktemp -d -t rcv-test-XXXXXX)
build_scaffolded_fixture "$T4" "1.0.0" "0.2.2" ""
"$SCRIPT" "$T4" round-1 >/dev/null 2>&1 || true
F=$(extract_forced "$T4")
[ "$F" = "false" ] || { echo "FAIL Test 4: empty seen expected forced_full=false; got $F"; exit 1; }
S=$(extract_seen "$T4")
[ "$S" = "0.2.2" ] || { echo "FAIL Test 4: first round should record seen=0.2.2; got '$S'"; exit 1; }
echo "PASS Test 4: first review → no auto-force, but seen baseline recorded"

# ─────────────────────────────────────────────────────────────────────────────
# Test 5 — Explicit --full overrides regardless
# ─────────────────────────────────────────────────────────────────────────────
T5=$(mktemp -d -t rcv-test-XXXXXX)
build_scaffolded_fixture "$T5" "1.0.0" "0.2.2" "0.2.2"
"$SCRIPT" --full "$T5" round-1 >/dev/null 2>&1 || true
F=$(extract_forced "$T5")
[ "$F" = "true" ] || { echo "FAIL Test 5: explicit --full expected forced_full=true; got $F"; exit 1; }
echo "PASS Test 5: explicit --full forces full regardless of version state"

# ─────────────────────────────────────────────────────────────────────────────
# Test 6 — NEGATIVE GUARD: target SKILL.md changes, scaffolder_version stays
# Simulates a writer/reviser editing target's SKILL.md (its own version bump
# in evolve-mode), with no scaffolder bump. MUST NOT force-full — that would
# defeat incremental review and re-evaluate the entire tree on every target
# version bump.
# ─────────────────────────────────────────────────────────────────────────────
T6=$(mktemp -d -t rcv-test-XXXXXX)
# target is now 2.0.0 (target self-bumped); provenance + seen still on 0.2.2
build_scaffolded_fixture "$T6" "2.0.0" "0.2.2" "0.2.2"
"$SCRIPT" "$T6" round-1 >/dev/null 2>&1 || true
F=$(extract_forced "$T6")
[ "$F" = "false" ] || {
  echo "FAIL Test 6: target self-bump (SKILL.md 1.0.0→2.0.0) WITHOUT scaffolder bump must NOT force-full; got $F"
  echo "  This would indicate run-checkers.sh is reading target SKILL.md instead of provenance — the 0.2.1 bug."
  exit 1
}
echo "PASS Test 6: target self-bump alone does NOT trigger force-full (negative guard against the 0.2.1 bug)"

echo "=== PASS test-run-checkers-version-drift.sh (6 sub-tests) ==="
