#!/usr/bin/env bash
# snapshot-leaves.sh — write a sha256 manifest of the design bundle's
# leaves at the start of a read phase. Consumed by compute-review-scope.sh
# on the next round to identify changed leaves for incremental review.
#
# Usage:
#   scripts/snapshot-leaves.sh <design-dir> <round>
#
# Output:
#   <design-dir>/.review/round-<N>/leaves-manifest.yml
#
# Exit codes (guide §9.1):
#   0  manifest written (single PASS line on stdout)
#   2  script error (bundle dir missing, IO error, etc.)
#
# The manifest covers README.md, modules/M-*.md, api/API-*.md, and
# architecture.md OR architecture/*.md as enumerated by
# sd_lint.enumerate_leaves(). Anything outside the artifact-bearing
# pattern (versions/, .review/) is excluded.

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <design-dir> <round>" >&2
  exit 2
fi

DESIGN_DIR="$1"
ROUND="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ ! -d "$DESIGN_DIR" ]]; then
  echo "ERROR: design-dir does not exist: $DESIGN_DIR" >&2
  exit 2
fi

if ! [[ "$ROUND" =~ ^[0-9]+$ ]]; then
  echo "ERROR: round must be a non-negative integer (got $ROUND)" >&2
  exit 2
fi

export DESIGN_DIR ROUND SCRIPT_DIR

python3 - <<'PYEOF'
import hashlib
import os
import subprocess
import sys
from datetime import datetime, timezone

DESIGN_DIR = os.environ["DESIGN_DIR"]
ROUND = int(os.environ["ROUND"])
SCRIPT_DIR = os.environ["SCRIPT_DIR"]

sys.path.insert(0, os.path.join(SCRIPT_DIR, "lib"))
from sd_lint import enumerate_leaves, fail_with_script_error  # type: ignore

round_dir = os.path.join(DESIGN_DIR, ".review", f"round-{ROUND}")
try:
    os.makedirs(round_dir, exist_ok=True)
except OSError as exc:
    fail_with_script_error(f"cannot create round dir {round_dir}: {exc}")

leaves = enumerate_leaves(DESIGN_DIR)

# Best-effort delivery_id discovery from <design-dir>/.review/state.yml
delivery_id = None
state_path = os.path.join(DESIGN_DIR, ".review", "state.yml")
if os.path.isfile(state_path):
    try:
        with open(state_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line.startswith("current_delivery:"):
                    delivery_id = line.split(":", 1)[1].strip()
                    break
    except OSError:
        delivery_id = None

git_sha = None
try:
    git_sha = subprocess.check_output(
        ["git", "-C", DESIGN_DIR, "rev-parse", "--short", "HEAD"],
        stderr=subprocess.DEVNULL,
        text=True,
    ).strip()
except (subprocess.CalledProcessError, FileNotFoundError, OSError):
    git_sha = None

manifest_path = os.path.join(round_dir, "leaves-manifest.yml")
generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")

lines: list[str] = []
lines.append("# Generated by snapshot-leaves.sh — do not edit by hand.")
lines.append(f"round: {ROUND}")
if delivery_id is not None:
    lines.append(f"delivery_id: {delivery_id}")
lines.append(f"generated_at: {generated_at}")
if git_sha:
    lines.append(f"git_sha: {git_sha}")
lines.append("leaves:")
if not leaves:
    lines.append("  []")

leaf_count = 0
for rel in leaves:
    full = os.path.join(DESIGN_DIR, rel)
    if not os.path.isfile(full):
        continue
    try:
        with open(full, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
    except OSError as exc:
        fail_with_script_error(f"cannot read leaf {rel}: {exc}")
    lines.append(f"  - path: {rel}")
    lines.append(f"    sha256: {digest}")
    leaf_count += 1

try:
    with open(manifest_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
except OSError as exc:
    fail_with_script_error(f"cannot write manifest {manifest_path}: {exc}")

print(f"PASS wrote leaves-manifest.yml with {leaf_count} leaf(es) for round-{ROUND}")
PYEOF
